//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMDGOINT.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int UsuariosWidth {
            get {
                return ((int)(this["UsuariosWidth"]));
            }
            set {
                this["UsuariosWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int UsuariosHeight {
            get {
                return ((int)(this["UsuariosHeight"]));
            }
            set {
                this["UsuariosHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point UsuariosLocation {
            get {
                return ((global::System.Drawing.Point)(this["UsuariosLocation"]));
            }
            set {
                this["UsuariosLocation"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://wsaahomo.afip.gov.ar/ws/services/LoginCms")]
        public string AMDGOINT_AFIP_HOMO_WSAA_LoginCMSService {
            get {
                return ((string)(this["AMDGOINT_AFIP_HOMO_WSAA_LoginCMSService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://wsaa.afip.gov.ar/ws/services/LoginCms")]
        public string AMDGOINT_AFIP_PROD_WSAA_LoginCMSService {
            get {
                return ((string)(this["AMDGOINT_AFIP_PROD_WSAA_LoginCMSService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://servicios1.afip.gov.ar/wsfev1/service.asmx")]
        public string AMDGOINT_AFIP_PROD_WSFE_Service {
            get {
                return ((string)(this["AMDGOINT_AFIP_PROD_WSFE_Service"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PrestatariaHeight {
            get {
                return ((int)(this["PrestatariaHeight"]));
            }
            set {
                this["PrestatariaHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PrestatariaWidth {
            get {
                return ((int)(this["PrestatariaWidth"]));
            }
            set {
                this["PrestatariaWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point PrestatariaLocation {
            get {
                return ((global::System.Drawing.Point)(this["PrestatariaLocation"]));
            }
            set {
                this["PrestatariaLocation"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://wswhomo.afip.gov.ar/wsfev1/service.asmx")]
        public string AMDGOINT_AFIP_HOMO_WSFE_Service {
            get {
                return ((string)(this["AMDGOINT_AFIP_HOMO_WSFE_Service"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ReporteHeight {
            get {
                return ((int)(this["ReporteHeight"]));
            }
            set {
                this["ReporteHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ReporteWidth {
            get {
                return ((int)(this["ReporteWidth"]));
            }
            set {
                this["ReporteWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point ReporteLocation {
            get {
                return ((global::System.Drawing.Point)(this["ReporteLocation"]));
            }
            set {
                this["ReporteLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int FacturaDetHeight {
            get {
                return ((int)(this["FacturaDetHeight"]));
            }
            set {
                this["FacturaDetHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int FacturaDetWidth {
            get {
                return ((int)(this["FacturaDetWidth"]));
            }
            set {
                this["FacturaDetWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point FacturaDetLocation {
            get {
                return ((global::System.Drawing.Point)(this["FacturaDetLocation"]));
            }
            set {
                this["FacturaDetLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int NcParamsHeight {
            get {
                return ((int)(this["NcParamsHeight"]));
            }
            set {
                this["NcParamsHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int NcParamsWidth {
            get {
                return ((int)(this["NcParamsWidth"]));
            }
            set {
                this["NcParamsWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point NcParamsLocation {
            get {
                return ((global::System.Drawing.Point)(this["NcParamsLocation"]));
            }
            set {
                this["NcParamsLocation"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://awshomo.afip.gov.ar/sr-padron/webservices/personaServiceA5")]
        public string AMDGOINT_WSPDR_HOMO_PersonaServiceA5 {
            get {
                return ((string)(this["AMDGOINT_WSPDR_HOMO_PersonaServiceA5"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://aws.afip.gov.ar/sr-padron/webservices/personaServiceA5")]
        public string AMDGOINT_WSPDR_PROD_PersonaServiceA5 {
            get {
                return ((string)(this["AMDGOINT_WSPDR_PROD_PersonaServiceA5"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ProfesHeight {
            get {
                return ((int)(this["ProfesHeight"]));
            }
            set {
                this["ProfesHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ProfesWidth {
            get {
                return ((int)(this["ProfesWidth"]));
            }
            set {
                this["ProfesWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point ProfesLocation {
            get {
                return ((global::System.Drawing.Point)(this["ProfesLocation"]));
            }
            set {
                this["ProfesLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ParamsPFCHeight {
            get {
                return ((int)(this["ParamsPFCHeight"]));
            }
            set {
                this["ParamsPFCHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ParamsPFCWidth {
            get {
                return ((int)(this["ParamsPFCWidth"]));
            }
            set {
                this["ParamsPFCWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point ParamsPFCLocation {
            get {
                return ((global::System.Drawing.Point)(this["ParamsPFCLocation"]));
            }
            set {
                this["ParamsPFCLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PlanesPopHeight {
            get {
                return ((int)(this["PlanesPopHeight"]));
            }
            set {
                this["PlanesPopHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PlanesPopWidth {
            get {
                return ((int)(this["PlanesPopWidth"]));
            }
            set {
                this["PlanesPopWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point PlanesPopLocation {
            get {
                return ((global::System.Drawing.Point)(this["PlanesPopLocation"]));
            }
            set {
                this["PlanesPopLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PresDetallesHeight {
            get {
                return ((int)(this["PresDetallesHeight"]));
            }
            set {
                this["PresDetallesHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PresDetallesWidth {
            get {
                return ((int)(this["PresDetallesWidth"]));
            }
            set {
                this["PresDetallesWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point PresDetallesLocation {
            get {
                return ((global::System.Drawing.Point)(this["PresDetallesLocation"]));
            }
            set {
                this["PresDetallesLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int InfoGeneralHeight {
            get {
                return ((int)(this["InfoGeneralHeight"]));
            }
            set {
                this["InfoGeneralHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int InfoGeneralWidth {
            get {
                return ((int)(this["InfoGeneralWidth"]));
            }
            set {
                this["InfoGeneralWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point InfoGeneralLocation {
            get {
                return ((global::System.Drawing.Point)(this["InfoGeneralLocation"]));
            }
            set {
                this["InfoGeneralLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int FacturaUnicHeight {
            get {
                return ((int)(this["FacturaUnicHeight"]));
            }
            set {
                this["FacturaUnicHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int FacturaUnicWidth {
            get {
                return ((int)(this["FacturaUnicWidth"]));
            }
            set {
                this["FacturaUnicWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point FacturaUnicLocation {
            get {
                return ((global::System.Drawing.Point)(this["FacturaUnicLocation"]));
            }
            set {
                this["FacturaUnicLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int FactUnicProfHeight {
            get {
                return ((int)(this["FactUnicProfHeight"]));
            }
            set {
                this["FactUnicProfHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int FactUnicProfWidth {
            get {
                return ((int)(this["FactUnicProfWidth"]));
            }
            set {
                this["FactUnicProfWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point FactUnicProfLocation {
            get {
                return ((global::System.Drawing.Point)(this["FactUnicProfLocation"]));
            }
            set {
                this["FactUnicProfLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int EspecialidadHeight {
            get {
                return ((int)(this["EspecialidadHeight"]));
            }
            set {
                this["EspecialidadHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int EspecialidadWidth {
            get {
                return ((int)(this["EspecialidadWidth"]));
            }
            set {
                this["EspecialidadWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point EspecialidadLocation {
            get {
                return ((global::System.Drawing.Point)(this["EspecialidadLocation"]));
            }
            set {
                this["EspecialidadLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PrestPopupHeight {
            get {
                return ((int)(this["PrestPopupHeight"]));
            }
            set {
                this["PrestPopupHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PrestPopupWidth {
            get {
                return ((int)(this["PrestPopupWidth"]));
            }
            set {
                this["PrestPopupWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point PrestPopupLocation {
            get {
                return ((global::System.Drawing.Point)(this["PrestPopupLocation"]));
            }
            set {
                this["PrestPopupLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PracticasHeight {
            get {
                return ((int)(this["PracticasHeight"]));
            }
            set {
                this["PracticasHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PracticasWidth {
            get {
                return ((int)(this["PracticasWidth"]));
            }
            set {
                this["PracticasWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point PracticasLocation {
            get {
                return ((global::System.Drawing.Point)(this["PracticasLocation"]));
            }
            set {
                this["PracticasLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Neg_coldifpedidoval {
            get {
                return ((bool)(this["Neg_coldifpedidoval"]));
            }
            set {
                this["Neg_coldifpedidoval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Neg_coldifpedidoporc {
            get {
                return ((bool)(this["Neg_coldifpedidoporc"]));
            }
            set {
                this["Neg_coldifpedidoporc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Neg_coldifpactadoval {
            get {
                return ((bool)(this["Neg_coldifpactadoval"]));
            }
            set {
                this["Neg_coldifpactadoval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Neg_coldifpactadoporc {
            get {
                return ((bool)(this["Neg_coldifpactadoporc"]));
            }
            set {
                this["Neg_coldifpactadoporc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Neg_coldifnomencval {
            get {
                return ((bool)(this["Neg_coldifnomencval"]));
            }
            set {
                this["Neg_coldifnomencval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Neg_coldifnomencporc {
            get {
                return ((bool)(this["Neg_coldifnomencporc"]));
            }
            set {
                this["Neg_coldifnomencporc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Neg_colcoseguro {
            get {
                return ((bool)(this["Neg_colcoseguro"]));
            }
            set {
                this["Neg_colcoseguro"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Neg_colcopago {
            get {
                return ((bool)(this["Neg_colcopago"]));
            }
            set {
                this["Neg_colcopago"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point EmpresaLocation {
            get {
                return ((global::System.Drawing.Point)(this["EmpresaLocation"]));
            }
            set {
                this["EmpresaLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int EmpresaWidth {
            get {
                return ((int)(this["EmpresaWidth"]));
            }
            set {
                this["EmpresaWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int EmpresaHeight {
            get {
                return ((int)(this["EmpresaHeight"]));
            }
            set {
                this["EmpresaHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Anl_colvalorpactant {
            get {
                return ((bool)(this["Anl_colvalorpactant"]));
            }
            set {
                this["Anl_colvalorpactant"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Anl_coldifpactporc {
            get {
                return ((bool)(this["Anl_coldifpactporc"]));
            }
            set {
                this["Anl_coldifpactporc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Rc_Impresion {
            get {
                return ((bool)(this["Rc_Impresion"]));
            }
            set {
                this["Rc_Impresion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ReclamoExportOption {
            get {
                return ((bool)(this["ReclamoExportOption"]));
            }
            set {
                this["ReclamoExportOption"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Ord_Impresion {
            get {
                return ((bool)(this["Ord_Impresion"]));
            }
            set {
                this["Ord_Impresion"] = value;
            }
        }
    }
}
